language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: TyD8N0yOKKuG4HHh862aSvPA9ARg/19n8sQu67gpVYx7MzrCUk3gmdLAwzQ6L4Ab6HXtfWswmwM75nWvT0ZVoP9uQAnGrRUiXdrWj7oOkWPuQVTz7Lrw1YHjSiidvJj4SPGR9lTZjgp3r8o4M8isPUMpENf7vxG8SzA+vMhiGbTeTz2PGP678nW7dkGXBAudvCXASgDwWBwTBY6h4HqQPQJJZnq/0kPfnGKHKAjodCBY0EABjgieBUtTgmBcGySJmKXqgKiIFOTPJCzTgdvo0rBXIwD5GDrWzsWl6x4BbalVjPXIEqOULjhNoHZvt84x3TKi7otGiEjjIe8dJZDNJUMqgnc370j0eEpSDmihWaXJf9ng21YkA3uXNTI55l0PTzqAJlTAbBGo6Xvdwf/a7WhFHw1/IZonA66AHj0R4qLsDnjUihKGJiZBnp00JoYTfpJZhTfkHNgyf6t9J8Bc6de3w+PudErSCicllbBLXiNU2WYARiYZmpfubsyfMp/3D+ssF+1buILTcNhOz8VZIUQ7m0plo5hpTsozR4r8LFKQtAtVJ1fwHpxJpNKKhxpR4+BwDiongfULxTixV7/lOcovb34cTi9mvTZF8X4XT4DhrCXLurE2Dnxt7L0fz7kOWT/pGqi2GUYbsQEwP/1J3ibRa/rVx6HUEUybHWJfnFE=
  app: kent-food-tracker
  on:
    repo: kenttoku/food-tracker-server
